baseurl = "https://skrzyneckik.github.io/wedding/"
languageCode = "en-us"
title = "RSVP for Agnieszka & Krzysztof Wedding"
theme = "hugo-creative-theme"
googleAnalytics = ""
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Agnieszka & Krzysztof - 1.09.2018"

		[params.navigation.links]
			about     = "Witamy/Welcome"
			location  = "Lokalizacja/Location"
			accomodation = "Zakwaterowanie/Accomodation"
			practical = "Practical information"
			contact   = "Kontakt/Contact"


	# Hero section
	[params.hero]
		slogan     = "Agnieszka & Krzysztof"
		subtitle   = "1.09.2018"
		buttonText = "Dowiedz się więcej/Find out more"


	# About section
	[params.about]
		headline_pl    = "Wspólnie z Rodzicami Agnieszka Suliga i Krzysztof Skrzynecki"
		subheadline_pl    = "Serdecznie zapraszają na uroczystość zaślubin"
		description_pl = "Sobota, 1 września 2018 o 16:00. Prosimy o potwierdzenie przybycia do 1 czerwca 2018"
		buttonText_pl = "Potwierdź teraz!"
		link_pl = "http://rsvp-pl.skrzyneckik.com"	
		headline    = "Together with their families Agnieszka Suliga and Krzysztof Skrzynecki"
		subheadline    = "Request the pleasure of your company to join the celebration of their wedding"
		description = "Saturday, 1st of September 2018 at 16:00. Kindly respond by 1st of June 2018"
		buttonText = "Confirm Now!"
		link = "http://rsvp.skrzyneckik.com"	

	# Service section
	#[params.services]
	#	headline = "At your service"

    #    [[params.services.list]]
    #        icon = "fa-diamond"
    #        title = "Sturdy Templates"
    #        description = "Our templates are updated regularly so they don't break."

    #    [[params.services.list]]
	#		icon = "fa-paper-plane"
	#		title = "Ready to Ship"
	#		description = "You can use this theme as is, or you can make changes!"

	#	[[params.services.list]]
    #        icon = "fa-newspaper-o"
    #        title = "Up to Date"
    #        description = "We update dependencies to keep things fresh."

    #    [[params.services.list]]
    #        icon = "fa-heart"
    #        title = "Made with Love"
    #        description = "You have to make your websites with love these days!"


    # Portfolio modals
	#[params.portfolio.modal]
    #   client = "Client"
    #   date = "Date"
    #   category = "Category"
    #   buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Accomodation section
	[params.accomodation]
		title    = "Zakwaterowanie / Accomodation"
		headline_pl    = "Drodzy Goście,"
		description_pl = "Dziękujemy szczególnie tym z Was którzy przyjadą z daleka. Dane dotyczące Waszego noclegu przekażemy Wam osobiście."

		headline    = "Dear Guests,"
		description    = "We appreciate your visit. We will share the details of your accommodation directly with you. We invite all guests from the UK to arrive on Friday."

	# Accomodation Dizzy Daisy section
	[params.accomodation_dizzy_daisy]
		title    = "Dizzy Daisy Downtown Hostel"
		headline    = "Pędzichów 9, 31-152, Krakow, Poland"
		description    = "Check in from 2 pm, Check out till 10am"

	# Accomodation Cracow Rent Apartments section
	[params.accomodation_cracow_rent_apartments]
		title    = "Cracow Rent Apartments"
		headline    = "Krowoderska 55, Stare Miasto, Kraków, 31-141, Poland"
		description    = "Getting into the property: Before you go to the property, you'll need to pick up the keys from: Krowoderska 65A, 31-151 Kraków.<br>You can pick up the keys to the property at the reception desk.<br><br>Phone: +48 733 770 360<br>Check in from 2pm, Check out till 11am"

	# Practical information
	[params.practical]
		title    = "First steps in Kraków"
		headline    = "Getting to and from the airport:"
		description    = "The airport is located about 20 min drive from the city centre. To get to your hostels from the airport please either:<ul><li>Train – leaves every hour and takes 18 min</li><li>Bus – leaves every hour as well and takes 40 min (replacement service for the train due to some construction work). This service leaves between the trains, so there is a way to get to the city every half an hour.</li></ul>Both train and bus tickets cost 9 Zloty (approx. £2). You can buy your ticket in one of the ticket machines, and pay either by card or cash. You can also buy a ticket inside the train, bus but only cash is accepted in this case. The station you are going to is Krakow Glowny (Krakow Main Station).<ul><li>Uber X should cost up to £10 (50 Zloty), please do not take a random taxi from in front of the airport, there is a risk that they might overcharge you seeing that you are foreiners. Alternatively ask how much in advance and if they say more than 50 Zloty it’s a scam!</li></ul>You can check the train times here: https://malopolskiekoleje.pl/index.php/pierwsza-strona"
		extra = "<br>From Krakow Main station you can walk to your accommodation, it’s close."

	# Wedding day
	[params.wedding]
		title    = "Wedding day"
		description    = "The ceremony starts at 16 pm sharp, please arrive about 15 min early and take a seat inside the church. You can take a tram or a bus to the church for cheap (tram stop Plac Bohaterów Getta or Smolki) but taking Uber from the hostel should be more comfortable and also cheap.<br><br>The ceremony should last up to 1h.<br><br>After the ceremony if it doesn’t rain we will take pictures and people queue to give greetings and gifts the newlyweds. It is polite to wait until this is over and after that please get to the bus which will take you to the reception venue. My sister Asia is supposed to be in charge of this and check if everyone is safe in the bus, but please look after one another because she is not very reliable 😉<br><br>Once you get to the reception venue, please walk from the parking and wait for us in front of the reception venue. The tradition says that the couple is welcomed with wine, bread and salt which symbolises luck and prosperity. After that just find your seat and wait for the dinner to be served 😊"

	# Sunday
	[params.sunday]
		title    = "Sunday"
		description = "Those who are staying on Sunday as well and invited to join us for a late brunch. This will be an in <b>Le Scandale</b> restaurant which is located in the Jewish district. Address: plac Nowy 9, 30-001 Kraków, Poland"

	# More info
	[params.more]
		title    = "More info"
		description = "The currency is Poland is Polish Zloty (PLN, literally Polish Gold 😉 )<br>You can pay by card almost everywhere, but I recommend that you have at least 50 Zloty in cash (£10) upon arrival. <br><Br>Poland is very annoying when it comes to paying by cash, if you are buying a small think and using a note such as 100 or 200 PLN the staff will often say that they have no change. In case that happens just tell them that’s it’s not your problem 😉 Worst case scenario and they really don’t have change be prepared to pay by card.<br><br>English is widely spoken in pubs and restaurants and even some shops in city centre.<br><br>Places worth visiting:<ul><li>Take a stroll on a Market square if its your first time in Krakow</li><li>Walk along Grodzka street to Wawel castle, climb up the hill and explore the castle if you have time</li><li>Walk or take a tram to the Jewish district, its full of bars, cafes and lovely little streets</li>"

	# Gift section
	[params.gift]
		title    = "Prezent / Gift"
		headline_pl    = "Drodzy Goście,"
		description_1_pl = "Najlepszym prezentem od Was będzie Wasza obecność z nami w tym najważniejszym dla nas dniu. Gdybyście życzyli sobie obdarować nas prezentem, będzie nam bardzo miło jeśli wspomożecie umeblowanie naszego mieszkania lub naszą podróż poslubną :)"
		description_2_pl = "Możecie to zrobić osobiście, lub jeśli wolicie używając przelewu bankowego. Prosimy skontaktujcie się z nami w celu podania danych."
		#account_pl = ""
		description_3_pl = "Będzie nam również bardzo miło jeśli zamiast kwiatów obdarujecie nas ważną dla Was książką, która mogłaby również nas ubogacić, lub ulubioną butelką wina, taką która szczególnie Wam smakuje, lub pochodzi z Waszego regionu. Dzięki temu Wasza obecność zostanie z nami na dłużej. Dziękujemy!"

		headline    = "Dear Guests,"
		description_1    = "The best wedding gift would be your presence! We would be very happy if you came to Cracow to celebrate with us this special occasion. However, if you wish to help us furnish the house, buy kitchen appliances or support our honeymoon ;) you can do it via a bank transfer or in person. We will share the bank details directly with you."
		#account = ""
		description_2    = "A few words of explanation. Traditionally, the newly weds receive gifts and congratulations after the church ceremony. People line up with gifts and congratulations and some smaller and more personal gifts. Those gifts depend on the couple’s request. If you would like to do the same, we are requesting books that are important for you and you think they could enrich us or a bottle of your favourite wine, one you particularly like or one that comes from your region. Please stick a note to it so we know it is from you :) This way, your presence at our wedding will last longer. Many thanks."

	# Contact section
	[params.contact]
		headline_pl = "Kontakt"
		description_pl = "W razie jakichkolwiek pytań prosimy o kontakt."
		phone_pl_1 = "+48 501 747 971 Agnieszka"
		phone_pl_2 = "+48 798 865 894 Krzysztof"
		headline = "Contact"
		description = "If you have any questions, please do ask!"
		phone_1 = "+44 07873931703 Agnieszka"
		phone_2 = "+44 07751018078 Krzysztof"
		email_1 = "agnieszka.suliga@gmail.com"
		email_2 = "skrzynecki.krzysztof@gmail.com"

	# Google Maps section
	[params.location]
		title    = "Lokalizacja / Location"
		headline_pl    = "Drodzy Goście, Nasz ślub odbędzie się w kościele pw. św. Józefa, na Rynku Podgórskim w Krakowie, dokładny adres to ul. Zamoyskiego 2, 30-523."
		description_pl = "Po uroczystości zaślubin serdecznie zapraszamy na przyjęcie weselne w Dworze w Tomaszowicach, ul. Krakowska 68, 32-085, Tomaszowice."

		headline    = "Church of St. Joseph, Zamoyskiego 2 street, 30-523 Cracow, Poland"
		description    = "Reception to follow at Dwór w Tomaszowicach, Krakowska 68 street, 32-085 Tomaszowice, Poland"

		latitude  = "50.0433063"
		longitude = "19.9477047"
	 	maps_api_key = "AIzaSyCafl1K6zv-oGKOHpkpDLsxSx6eXvBvAXs"
